spring:
  application:
    name: easylearn-note
  data:
    mongodb:
      database: note
      host: notedb
server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
      enabled: true